# Generated by Django 4.1 on 2024-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary_app', '0003_appointment_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
