# Generated by Django 4.1 on 2024-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary_app', '0005_appointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
